// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

exports.VerticaError = (function(_super) {
  __extends(VerticaError, _super);

  function VerticaError(message) {
    this.message = message;
    VerticaError.__super__.constructor.call(this, this.message);
  }

  return VerticaError;

})(Error);

exports.ConnectionError = (function(_super) {
  __extends(ConnectionError, _super);

  function ConnectionError() {
    return ConnectionError.__super__.constructor.apply(this, arguments);
  }

  return ConnectionError;

})(exports.VerticaError);

exports.QueryError = (function(_super) {
  __extends(QueryError, _super);

  function QueryError() {
    return QueryError.__super__.constructor.apply(this, arguments);
  }

  return QueryError;

})(exports.VerticaError);

exports.QueryErrorResponse = (function(_super) {
  __extends(QueryErrorResponse, _super);

  function QueryErrorResponse(msg) {
    QueryErrorResponse.__super__.constructor.call(this, msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

  return QueryErrorResponse;

})(exports.QueryError);

exports.CopyDataError = (function(_super) {
  __extends(CopyDataError, _super);

  function CopyDataError() {
    return CopyDataError.__super__.constructor.apply(this, arguments);
  }

  return CopyDataError;

})(exports.VerticaError);
