// Generated by CoffeeScript 1.9.0
var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

exports.VerticaError = (function(_super) {
  __extends(VerticaError, _super);

  function VerticaError(_at_message) {
    this.message = _at_message;
    VerticaError.__super__.constructor.call(this, this.message);
  }

  return VerticaError;

})(Error);

exports.ConnectionError = (function(_super) {
  __extends(ConnectionError, _super);

  function ConnectionError() {
    return ConnectionError.__super__.constructor.apply(this, arguments);
  }

  return ConnectionError;

})(exports.VerticaError);

exports.ConnectionErrorResponse = (function(_super) {
  __extends(ConnectionErrorResponse, _super);

  function ConnectionErrorResponse(msg) {
    ConnectionErrorResponse.__super__.constructor.call(this, msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

  return ConnectionErrorResponse;

})(exports.ConnectionError);

exports.AuthenticationError = (function(_super) {
  __extends(AuthenticationError, _super);

  function AuthenticationError() {
    return AuthenticationError.__super__.constructor.apply(this, arguments);
  }

  return AuthenticationError;

})(exports.ConnectionErrorResponse);

exports.SSLError = (function(_super) {
  __extends(SSLError, _super);

  function SSLError() {
    return SSLError.__super__.constructor.apply(this, arguments);
  }

  return SSLError;

})(exports.ConnectionError);

exports.ClientStateError = (function(_super) {
  __extends(ClientStateError, _super);

  function ClientStateError() {
    return ClientStateError.__super__.constructor.apply(this, arguments);
  }

  return ClientStateError;

})(exports.VerticaError);

exports.QueryError = (function(_super) {
  __extends(QueryError, _super);

  function QueryError() {
    return QueryError.__super__.constructor.apply(this, arguments);
  }

  return QueryError;

})(exports.VerticaError);

exports.QueryErrorResponse = (function(_super) {
  __extends(QueryErrorResponse, _super);

  function QueryErrorResponse(msg) {
    QueryErrorResponse.__super__.constructor.call(this, msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

  return QueryErrorResponse;

})(exports.QueryError);
