// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.VerticaError = (function(superClass) {
  extend(VerticaError, superClass);

  function VerticaError(message) {
    this.message = message;
    VerticaError.__super__.constructor.call(this, this.message);
  }

  return VerticaError;

})(Error);

exports.ConnectionError = (function(superClass) {
  extend(ConnectionError, superClass);

  function ConnectionError() {
    return ConnectionError.__super__.constructor.apply(this, arguments);
  }

  return ConnectionError;

})(exports.VerticaError);

exports.ConnectionErrorResponse = (function(superClass) {
  extend(ConnectionErrorResponse, superClass);

  function ConnectionErrorResponse(msg) {
    ConnectionErrorResponse.__super__.constructor.call(this, msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

  return ConnectionErrorResponse;

})(exports.ConnectionError);

exports.AuthenticationError = (function(superClass) {
  extend(AuthenticationError, superClass);

  function AuthenticationError() {
    return AuthenticationError.__super__.constructor.apply(this, arguments);
  }

  return AuthenticationError;

})(exports.ConnectionErrorResponse);

exports.SSLError = (function(superClass) {
  extend(SSLError, superClass);

  function SSLError() {
    return SSLError.__super__.constructor.apply(this, arguments);
  }

  return SSLError;

})(exports.ConnectionError);

exports.ClientStateError = (function(superClass) {
  extend(ClientStateError, superClass);

  function ClientStateError() {
    return ClientStateError.__super__.constructor.apply(this, arguments);
  }

  return ClientStateError;

})(exports.VerticaError);

exports.QueryError = (function(superClass) {
  extend(QueryError, superClass);

  function QueryError() {
    return QueryError.__super__.constructor.apply(this, arguments);
  }

  return QueryError;

})(exports.VerticaError);

exports.QueryErrorResponse = (function(superClass) {
  extend(QueryErrorResponse, superClass);

  function QueryErrorResponse(msg) {
    QueryErrorResponse.__super__.constructor.call(this, msg.information['Message']);
    this.fields = msg.information;
    this.code = msg.information['Code'];
  }

  return QueryErrorResponse;

})(exports.QueryError);
