// Generated by CoffeeScript 1.11.1
var FrontendMessage,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  slice = [].slice;

import { AuthenticationMethods } from './authentication.js'
import { Buffer } from './buffer.js'

FrontendMessage = (function() {
  function FrontendMessage() {}

  FrontendMessage.prototype.typeId = null;

  FrontendMessage.prototype.payload = function() {
    return Buffer.alloc(0);
  };

  FrontendMessage.prototype.toBuffer = function() {
    var b, bLength, headerLength, messageBuffer, payloadBuffer, pos;
    payloadBuffer = this.payload();
    if (typeof payloadBuffer === 'string') {
      bLength = Buffer.byteLength(payloadBuffer);
      b = Buffer.alloc(bLength + 1);
      b.writeZeroTerminatedString(payloadBuffer, 0);
      payloadBuffer = b;
    }
    headerLength = this.typeId != null ? 5 : 4;
    messageBuffer = Buffer.alloc(headerLength + payloadBuffer.length);
    if (this.typeId) {
      messageBuffer.writeUInt8(this.typeId, 0);
      pos = 1;
    } else {
      pos = 0;
    }
    messageBuffer.writeUInt32BE(payloadBuffer.length + 4, pos);
    payloadBuffer.copy(messageBuffer, pos + 4);
    return messageBuffer;
  };

  return FrontendMessage;

})();

FrontendMessage.Startup = (function(superClass) {
  extend(Startup, superClass);

  Startup.prototype.typeId = null;

  Startup.prototype.protocol = 3 << 16;

  function Startup(user, database, options) {
    this.user = user;
    this.database = database;
    this.options = options;
  }

  Startup.prototype.payload = function() {
    var pl, pos;
    pos = 0;
    pl = Buffer.alloc(8192);
    pl.writeUInt32BE(this.protocol, pos);
    pos += 4;
    if (this.user) {
      pos += pl.writeZeroTerminatedString('user', pos);
      pos += pl.writeZeroTerminatedString(this.user, pos);
    }
    if (this.database) {
      pos += pl.writeZeroTerminatedString('database', pos);
      pos += pl.writeZeroTerminatedString(this.database, pos);
    }
    if (this.options) {
      pos += pl.writeZeroTerminatedString('options', pos);
      pos += pl.writeZeroTerminatedString(this.options, pos);
    }
    pl.writeUInt8(0, pos);
    pos += 1;
    return pl.slice(0, pos);
  };

  return Startup;

})(FrontendMessage);

FrontendMessage.SSLRequest = (function(superClass) {
  extend(SSLRequest, superClass);

  function SSLRequest() {
    return SSLRequest.__super__.constructor.apply(this, arguments);
  }

  SSLRequest.prototype.typeId = null;

  SSLRequest.prototype.sslMagicNumber = 80877103;

  SSLRequest.prototype.payload = function() {
    var pl;
    pl = Buffer.alloc(4);
    pl.writeUInt32BE(this.sslMagicNumber, 0);
    return pl;
  };

  return SSLRequest;

})(FrontendMessage);

FrontendMessage.Password = (function(superClass) {
  extend(Password, superClass);

  Password.prototype.typeId = 112;

  function Password(password, authMethod, options) {
    this.password = password;
    this.authMethod = authMethod;
    this.options = options;
    if (this.password == null) {
      this.password = '';
    }
    if (this.authMethod == null) {
      this.authMethod = AuthenticationMethods.CLEARTEXT_PASSWORD;
    }
    if (this.options == null) {
      this.options = {};
    }
  }

  Password.prototype.md5 = function() {
    var hash, i, len, value, values;
    values = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    hash = require('crypto').createHash('md5');
    for (i = 0, len = values.length; i < len; i++) {
      value = values[i];
      hash.update(value);
    }
    return hash.digest('hex');
  };

  Password.prototype.encodedPassword = function() {
    var salt;
    switch (this.authMethod) {
      case AuthenticationMethods.CLEARTEXT_PASSWORD:
        return this.password;
      case AuthenticationMethods.MD5_PASSWORD:
        salt = Buffer.alloc(4);
        salt.writeUInt32BE(this.options.salt, 0);
        return "md5" + this.md5(this.md5(this.password, this.options.user), salt);
      default:
        throw new Error("Authentication method " + this.authMethod + " not implemented.");
    }
  };

  Password.prototype.payload = function() {
    return this.encodedPassword();
  };

  return Password;

})(FrontendMessage);

FrontendMessage.CancelRequest = (function(superClass) {
  extend(CancelRequest, superClass);

  CancelRequest.prototype.cancelRequestMagicNumber = 80877102;

  function CancelRequest(backendPid, backendKey) {
    this.backendPid = backendPid;
    this.backendKey = backendKey;
  }

  CancelRequest.prototype.payload = function() {
    var b;
    b = Buffer.alloc(12);
    b.writeUInt32BE(this.cancelRequestMagicNumber, 0);
    b.writeUInt32BE(this.backendPid, 4);
    b.writeUInt32BE(this.backendKey, 8);
    return b;
  };

  return CancelRequest;

})(FrontendMessage);

FrontendMessage.Close = (function(superClass) {
  extend(Close, superClass);

  Close.prototype.typeId = 67;

  function Close(type, name) {
    this.name = name;
    if (this.name == null) {
      this.name = "";
    }
    this.type = (function() {
      switch (type) {
        case 'portal':
        case 'p':
        case 'P':
        case 80:
          return 80;
        case 'prepared_statement':
        case 'prepared':
        case 'statement':
        case 's':
        case 'S':
        case 83:
          return 83;
        default:
          throw new Error(type + " not a valid type to describe");
      }
    })();
  }

  Close.prototype.payload = function() {
    let b = Buffer.alloc(this.name.length + 2);
    b.writeUInt8(this.type, 0);
    b.writeZeroTerminatedString(this.name, 1);
    return b;
  };

  return Close;

})(FrontendMessage);

FrontendMessage.Describe = (function(superClass) {
  extend(Describe, superClass);

  Describe.prototype.typeId = 68;

  function Describe(type, name) {
    this.name = name;
    if (this.name == null) {
      this.name = "";
    }
    this.type = (function() {
      switch (type) {
        case 'portal':
        case 'P':
        case 80:
          return 80;
        case 'prepared_statement':
        case 'prepared':
        case 'statement':
        case 'S':
        case 83:
          return 83;
        default:
          throw new Error(type + " not a valid type to describe");
      }
    })();
  }

  Describe.prototype.payload = function() {
    var b;
    b = Buffer.alloc(this.name.length + 2);
    b.writeUInt8(this.type, 0);
    b.writeZeroTerminatedString(this.name, 1);
    return b;
  };

  return Describe;

})(FrontendMessage);

FrontendMessage.Execute = (function(superClass) {
  extend(Execute, superClass);

  Execute.prototype.typeId = 69;

  function Execute(portal, maxRows) {
    this.portal = portal;
    this.maxRows = maxRows;
    if (this.portal == null) {
      this.portal = "";
    }
    if (this.maxRows == null) {
      this.maxRows = 0;
    }
  }

  Execute.prototype.payload = function() {
    var b, pos;
    b = Buffer.alloc(5 + this.portal.length);
    pos = b.writeZeroTerminatedString(this.portal, 0);
    b.writeUInt32BE(this.maxRows, pos);
    return b;
  };

  return Execute;

})(FrontendMessage);

FrontendMessage.Query = (function(superClass) {
  extend(Query, superClass);

  Query.prototype.typeId = 81;

  function Query(sql) {
    this.sql = sql;
  }

  Query.prototype.payload = function() {
    return this.sql;
  };

  return Query;

})(FrontendMessage);

FrontendMessage.Parse = (function(superClass) {
  extend(Parse, superClass);

  Parse.prototype.typeId = 80;

  function Parse(name, sql, parameterTypes) {
    this.name = name;
    this.sql = sql;
    this.parameterTypes = parameterTypes;
    if (this.name == null) {
      this.name = "";
    }
    if (this.parameterTypes == null) {
      this.parameterTypes = [];
    }
  }

  Parse.prototype.payload = function() {
    var b, i, len, paramType, pos, ref;
    b = Buffer.alloc(8192);
    pos = b.writeZeroTerminatedString(this.name, 0);
    pos += b.writeZeroTerminatedString(this.sql, pos);
    b.writeUInt16BE(this.parameterTypes.length, pos);
    pos += 2;
    ref = this.parameterTypes;
    for (i = 0, len = ref.length; i < len; i++) {
      paramType = ref[i];
      b.writeUInt32BE(paramType, pos);
      pos += 4;
    }
    return b.slice(0, pos);
  };

  return Parse;

})(FrontendMessage);

FrontendMessage.Bind = (function(superClass) {
  extend(Bind, superClass);

  Bind.prototype.typeId = 66;

  function Bind(portal, preparedStatement, parameterValues) {
    var i, len, parameterValue;
    this.portal = portal;
    this.preparedStatement = preparedStatement;
    this.parameterValues = [];
    for (i = 0, len = parameterValues.length; i < len; i++) {
      parameterValue = parameterValues[i];
      this.parameterValues.push(parameterValue.toString());
    }
  }

  Bind.prototype.payload = function() {
    var b, i, len, pos, ref, value;
    b = Buffer.alloc(8192);
    pos = 0;
    pos += b.writeZeroTerminatedString(this.portal, pos);
    pos += b.writeZeroTerminatedString(this.preparedStatement, pos);
    b.writeUInt16BE(0x00, pos);
    b.writeUInt16BE(this.parameterValues.length, pos + 2);
    pos += 4;
    ref = this.parameterValues;
    for (i = 0, len = ref.length; i < len; i++) {
      value = ref[i];
      b.writeUInt32BE(value.length, pos);
      pos += 4;
      pos += b.write(value, pos);
    }
    return b.slice(0, pos);
  };

  return Bind;

})(FrontendMessage);

FrontendMessage.Flush = (function(superClass) {
  extend(Flush, superClass);

  function Flush() {
    return Flush.__super__.constructor.apply(this, arguments);
  }

  Flush.prototype.typeId = 72;

  return Flush;

})(FrontendMessage);

FrontendMessage.Sync = (function(superClass) {
  extend(Sync, superClass);

  function Sync() {
    return Sync.__super__.constructor.apply(this, arguments);
  }

  Sync.prototype.typeId = 83;

  return Sync;

})(FrontendMessage);

FrontendMessage.Terminate = (function(superClass) {
  extend(Terminate, superClass);

  function Terminate() {
    return Terminate.__super__.constructor.apply(this, arguments);
  }

  Terminate.prototype.typeId = 88;

  return Terminate;

})(FrontendMessage);

FrontendMessage.CopyData = (function(superClass) {
  extend(CopyData, superClass);

  CopyData.prototype.typeId = 100;

  function CopyData(data) {
    this.data = data;
  }

  CopyData.prototype.payload = function() {
    return new Buffer(this.data);
  };

  return CopyData;

})(FrontendMessage);

FrontendMessage.CopyDone = (function(superClass) {
  extend(CopyDone, superClass);

  function CopyDone() {
    return CopyDone.__super__.constructor.apply(this, arguments);
  }

  CopyDone.prototype.typeId = 99;

  return CopyDone;

})(FrontendMessage);

FrontendMessage.CopyFail = (function(superClass) {
  extend(CopyFail, superClass);

  CopyFail.prototype.typeId = 102;

  function CopyFail(error) {
    this.error = error;
  }

  CopyFail.prototype.payload = function() {
    return this.error;
  };

  return CopyFail;

})(FrontendMessage);

export { FrontendMessage }