// Generated by CoffeeScript 1.6.2
(function() {
  var Resultset;

  Resultset = (function() {
    function Resultset(object) {
      this.fields = object.fields || [];
      this.rows = object.rows || [];
      this.notices = object.notices || [];
      this.status = object.status;
    }

    Resultset.prototype.theValue = function() {
      return this.rows[0][0];
    };

    Resultset.prototype.getLength = function() {
      return this.rows.length;
    };

    return Resultset;

  })();

  module.exports = Resultset;

}).call(this);
